theme: minima

# Social networks
twitter_username: kreykjalin
github_username: reykjalin
linkedin_username: kristoferrt
rss: rss

# Nav bar pages
header_pages:
  - about.md

# Show post excerpts
# show_excerpts: true
