theme: minima
title: reykjal.in
email: kris@reykjal.in
description: >
  A blog to write down my thoughts on issues I encounter in my work and
  personal projects.

# Social networks
twitter_username: kreykjalin
github_username: reykjalin
linkedin_username: kristoferrt
# rss: rss

# Nav bar pages
header_pages:
  - projects.md
  - about.md

# Show post excerpts
# show_excerpts: true

# Enable comments
# disqus:
#   shortname: reykjal-in
